CREATE DATABASE QuanLyDatVe
GO

USE QuanLyDatVe
GO

CREATE TABLE KhachHang
(
	maKH INT PRIMARY KEY,
	hoTen NVARCHAR(50) NOT NULL,
	soDienThoai VARCHAR(10) NOT NULL
)
GO

CREATE TABLE Xe
(
	maXe INT PRIMARY KEY,
	bienSo VARCHAR(10) NOT NULL,
	taiXe NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE ChuyenDi
(
	maCD INT PRIMARY KEY,
	gioDi INT NOT NULL,
	ngayDi DATETIME NOT NULL,
	diemDi NVARCHAR(50) NOT NULL,
	diemDen NVARCHAR(50) NOT NULL,
	giaVe FLOAT NOT NULL,
	maXe INT NOT NULL,
	FOREIGN KEY (maXe) REFERENCES dbo.Xe
)
GO

CREATE TABLE Ve
(
	maKH INT,
	maCD INT,
	thoiGianDat DATETIME NOT NULL,
	PRIMARY KEY (maKH, maCD), 
	FOREIGN KEY (maKH) REFERENCES dbo.KhachHang,
	FOREIGN KEY (maCD) REFERENCES dbo.ChuyenDi
)
GO
